apiVersion: apps/v1
kind: Deployment
metadata:
  name: site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
      - name: site
        image: jmarinoni/utn:v1.2
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_DATABASE
          value: "rest_api"
        - name: MYSQL_USER
          value: "my_user"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_PASSWORD
        - name: DB_HOST
          value: "mysql"
        - name: DB_CHARSET
          value: "utf8"
        - name: DB_NAME
          value: "rest_api"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: site
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: site
